apiVersion: v1
kind: Service
metadata:
  name: web-app
  namespace: web-app
spec:
  type: LoadBalancer
  selector:
    app: dotnet-worker-image
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000